on: [pull_request]

jobs:
  add_pr_comment:
    permissions: write-all
    runs-on: ubuntu-latest
    name: OpenAI PR Comment
    steps:
      - name: action-gpt
      uses: dciborow/action-gpt@0.0.9
